apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: staging
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: gvenkat/webapp1:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
